### ISSUE TITLE
arch mismatch in doc

### ISSUE THREAD

**Issue by kbumsik** [deployKF/cli#10]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/cli/issues).

### deployKF CLI Version

0.1.0

### Description

Hi. Thanks for an interesting project!

[The doc](https://www.deploykf.org/guides/install-deploykf-cli/) uses `uname -m` to figure out the target arch on Linux.

```
DKF_CLI_VERSION="0.1.0"
DKF_CLI_ARCH="$(uname -m)"
DFK_CLI_DEST=/usr/local/bin/deploykf

# download the binary
sudo curl -L "https://github.com/deploykf/cli/releases/download/v${DKF_CLI_VERSION}/deploykf-linux-${DKF_CLI_ARCH}" -o "${DFK_CLI_DEST}"

# make the binary executable
sudo chmod +x "${DFK_CLI_DEST}"

# test the binary
deploykf version
```

However, in our machine ([Lambda Labs Cloud](https://lambdalabs.com/) 8x A100 40GB machine), `uname -m` reports `x86_64`, whereas [the release](https://github.com/deployKF/cli/releases/tag/v0.1.0) assumes `amd64`.

So, just copying and paste the above code **downloads an empty file without an error**, and `deploykf version` executes the empty file and prints `/usr/local/bin/deploykf: 1: Not: not found`

Here are my suggestions:
1. Add `x84_64` in release
2. `sudo curl -L` -> `sudo curl -fL`. With [`-f` flag](https://superuser.com/a/657174/674579) curl will safely non-0 exit when not found, with no file downloaded.

**Comment by thesuperzapper** [comment]
@kbumsik thanks for reporting this!

I have resolved the issue in https://github.com/deployKF/website/pull/45

I used `uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/'` but the `curl -f` flag was also a great idea, it helps people know when there is not currently a pre-built CLI binary for their architecture.

**Comment by kbumsik** [comment]
> I used uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/' 

Nice trick 👍 

Thanks for the quick response. Let me try deploykf today. I am testing Kubeflow on a 8x A100 server on k3s.
